Use master
Go

--- Segunda ejecución
CREATE DATABASE BDPLANILLA
Go

--- Tercera ejecución
USE BDPLANILLA

CREATE TABLE TBSALARIOS
(
	ID int NOT NULL IDENTITY(1,1),
	CDEMPLEADO int NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(15) NOT NULL,
	APELLIDOS VARCHAR(20) NOT NULL,
	DEPARTAMENTO VARCHAR(25) NOT NULL,
	TELEFONO VARCHAR(15),
	SALARIOMENSUAL FLOAT,
	CCSS FLOAT,
	BANCOPOPULAR FLOAT,
	FECHADEPAGO DATE
)

--- Cuarta ejecución: agregamos 2 registros para cargar la tabla de datos
insert INTO TBSALARIOS(CDEMPLEADO,NOMBRE,APELLIDOS,DEPARTAMENTO,TELEFONO,SALARIOMENSUAL,CCSS,BANCOPOPULAR,FECHADEPAGO)
VALUES(31,'Elsi','Garro Mata','TI','8888-8888',100000,9340,1000,'1/01/2018')

insert INTO TBSALARIOS(CDEMPLEADO,NOMBRE,APELLIDOS,DEPARTAMENTO,TELEFONO,SALARIOMENSUAL,CCSS,BANCOPOPULAR,FECHADEPAGO)
VALUES(32,'Noe','Picado Piedras','Contabilidad','9999-9999',200000,18680,2000,'1/01/2018')

--- Quinta ejecución: ver registros
select*from TBSALARIOS

--- Registrar pago
CREATE PROCEDURE [dbo].[GUARDAR_SALARIO]
-- ADD THE PARAMETERS FOR THE STORED PROCEDURE HERE

@ID INT OUT,
@CDEMPLEADO INT,
@NOMBRE VARCHAR(20),
@APELLIDOS VARCHAR(20),
@DEPARTAMENTO VARCHAR(25),
@TELEFONO VARCHAR(15),
@SALARIOMENSUAL FLOAT,
@CCSS FLOAT,
@BANCOPOPULAR FLOAT,
@FECHADEPAGO DATE,
@MSJ VARCHAR(50) OUT

AS 
	BEGIN
			INSERT INTO TBSALARIOS(CDEMPLEADO,NOMBRE,APELLIDOS,DEPARTAMENTO,TELEFONO,SALARIOMENSUAL,CCSS,BANCOPOPULAR,FECHADEPAGO)
			VALUES(@CDEMPLEADO,@NOMBRE,@APELLIDOS,@DEPARTAMENTO,@TELEFONO,@SALARIOMENSUAL,@CCSS,@BANCOPOPULAR,@FECHADEPAGO)
			SELECT @ID = IDENT_CURRENT('dbo.TBSALARIOS')
			SET @MSJ = 'EL MOVIMIENTO DE PLANILLA FUE AGREGADO EXITOSAMENTE'

	END

--- Eliminar salario
CREATE PROCEDURE [dbo].[ELIMINAR]
-- ADD THE PARAMETERS FOR THE STORED PROCEDURE HERE

@CDEMPLEADO INT,
@MSJ VARCHAR(50) OUT

AS
	BEGIN
		IF (NOT EXISTS(SELECT*FROM TBSALARIOS WHERE CDEMPLEADO = @CDEMPLEADO))
			SET @MSJ = 'NO EXISTE CÉDULA DE EMPLEADO INGRESADO !!!'
		ELSE
			BEGIN
				DELETE FROM TBSALARIOS WHERE CDEMPLEADO = @CDEMPLEADO
				SET @MSJ = 'EL TRABAJADOR HA SIDO ELIMINADO EXITOSAMENTE !!!'
			END
	END

--- Consultar pago
CREATE PROCEDURE [dbo].[BUSCAR]
-- ADD THE PARAMETERS FOR THE STORED PROCEDURE HERE

@CDEMPLEADO INT,
@MSJ VARCHAR(50) OUT

AS
	BEGIN
		IF (NOT EXISTS(SELECT * FROM TBSALARIOS WHERE CDEMPLEADO=@CDEMPLEADO))
			SET @MSJ = 'EL TRABAJADOR NO EXISTE !!! '
		ELSE
			BEGIN
				SELECT * FROM  TBSALARIOS WHERE CDEMPLEADO = @CDEMPLEADO
				SET @MSJ = ' EL EMPLEADO HA SIDO ENCONTRADO !!!'
			END
	END